### create report
POST http://localhost:4000/reports
Content-Type: application/json

{
  "price":5031,
  "make":"bmw",
  "model":"corolla",
  "year":1980,
  "mileage":20000,
  "lat":"0",
  "lng":"0",
  "approved":true
}

### update a report
PATCH http://localhost:4000/reports/1
Content-Type: application/json

{
  "approved":true
}

### get estimate
GET http://localhost:4000/reports?make=bmw&model=corolla&lng=0&lat=0&mileage=20000&year=1980
Content-Type: application/json
