### create a new user
POST http://localhost:4000/auth/sign-up
Content-Type: application/json

{
  "email":"asd@asd.com",
  "password":"123"
}


### validate a user
POST http://localhost:4000/auth/sign-in
Content-Type: application/json

{
  "email":"asd@asd.com",
  "password":"123"
}

### who am i
GET http://localhost:4000/auth/whoami

### sign out
POST  http://localhost:4000/auth/sign-out




### find a particular user with a given id
GET http://localhost:4000/auth/1


### find all users with this email
GET http://localhost:4000/auth?email=asd@asd.com

### delete a user given id
DELETE http://localhost:4000/auth/1

### update a user
PATCH http://localhost:4000/auth/1
Content-Type: application/json

{
  "email":"asd1@asd.com",
  "password":"12344"
}
